In [56]:
#Создание ортоганальной диагональной матрицы матрицы
import numpy as np
A = np.array ([[0,1,0], [0,0,1], [1,0,0]])
A

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [57]:
#Создание транcпонированной матрицы
T = A.transpose()
A.dot(T)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [58]:
#Проверка на ортогональность
E = T@A
E

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [63]:
#Верхнетреугольная, ортогональная
A = np.array ([[1,0,0], [0,1,0], [0,0,1]])
A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [64]:
#Создание транcпонированной матрицы
T = A.transpose()
A.dot(T)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [65]:
#Проверка на ортогональность
E = T@A
E

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [81]:
#Нижнетреугольная, ортогональная
A = np.array ([[-1,0,0], [0,-1,0], [0,0,1]])
A

array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  1]])

In [82]:
#Создание транcпонированной матрицы
T = A.transpose()
A.dot(T)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [83]:
#Проверка на ортогональность
E = T@A
E

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [105]:
#Матрица, у которой определитель = 1, и все элементы не равны 0
A = np.array ([[3,1], [2,1]])
A 

array([[3, 1],
       [2, 1]])

In [115]:
#собственные значения и собственные вектора матриц:
from numpy import linalg as LA
m = np.array([[2, 2], [1, 3]])
w,v = LA.eig(m)
print(w)
print(v)


[1. 4.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [124]:
#
m = np.array([[1, 2], [2,3]])
D = np.diag(m)
A = np.array([[-1, 0], [0,-1]])
T = A.transpose()
A.dot(T)


array([[1, 0],
       [0, 1]])

In [125]:
E = T@A
E

array([[1, 0],
       [0, 1]])

In [126]:
X = T@D@E
X

array([-1, -3])